"""Type stubs for the torch-free native metadata module.

Generated by ``scripts/gen_native_stub.py`` — do not edit by hand. Run
``python -m pytest tests/test_native_stub.py`` after changing the C++
bindings; a mismatch between this file and the extension fails the build.

``torchfits._core`` is a nanobind module over ``libtorchfits_core``, which links
CFITSIO and nothing else. Nothing here may ever return a ``torch.Tensor``: the
whole reason this module exists is that the metadata path must not load
libtorch.
"""

from collections.abc import Sequence
from typing import Any

__build_id__: str

__core_api_version__: int

TORCH_FREE: bool

def core_library_build_id() -> str: ...

def thread_count() -> int: ...

class Metadata:
    """
    Read-only FITS handle for metadata queries. Holds no tensor state.

    Axis order differs between two of the accessors on purpose: ``shape()``
    is row-major (NAXISn reversed), ``image_info()`` is FITS NAXISn order.
    See each method's docstring before mixing them.
    """

    def __init__(self, path: str) -> None: ...

    def num_hdus(self) -> int: ...

    def hdu_type(self, hdu: int) -> str: ...

    def shape(self, hdu: int) -> list[int]:
        """
        Row-major (torch order) shape: NAXISn reversed.

        This is the shape the tensor paths use. ``image_info()`` returns
        the same dimensions in FITS NAXISn order instead.
        """

    def bitpix(self, hdu: int) -> int: ...

    def nrows(self, hdu: int) -> int: ...

    def colnames(self, hdu: int) -> list[str]: ...

    def table_info(self, hdu: int) -> dict[str, Any]: ...

    def keywords(self, hdu: int, keys: Sequence[str]) -> dict[str, Any]: ...

    def header(self, hdu: int) -> list[Any]: ...

    def header_text(self, hdu: int) -> str: ...

    def scale_info(self, hdu: int) -> tuple[bool, bool, float, float]: ...

    def image_info(self, hdu: int) -> tuple[int, int, tuple[int, ...]]:
        """
        (bitpix, naxis, (NAXIS1 .. NAXISn)) in FITS order, NOT row-major.

        The axis tuple is *not* the shape: it is NAXIS1 first, so for a
        non-square HDU it is the transpose of ``shape()``. Callers that
        want a torch shape want ``shape()``; this one exists to report
        NAXISn as written, e.g. to compare against a header.
        """

    def is_compressed_image(self, hdu: int) -> bool: ...

    def close(self) -> None: ...

    def closed(self) -> bool: ...

    def __enter__(self) -> Metadata: ...

    def __exit__(self, exc_type: object | None, exc_value: object | None, traceback: object | None) -> bool: ...

    def __repr__(self) -> str: ...

def read_header_dict(filename: str, hdu_num: int) -> list[tuple[str, str, str]]: ...

def read_header_string(filename: str, hdu_num: int) -> str: ...

def read_num_hdus(filename: str) -> int: ...

def read_hdu_type(filename: str, hdu_num: int) -> str: ...

def read_nrows(filename: str, hdu_num: int) -> int: ...

def read_colnames(filename: str, hdu_num: int) -> list[str]: ...

def read_table_info(filename: str, hdu_num: int) -> dict[str, Any]: ...

def read_keys(filename: str, hdu_num: int, keys: Sequence[str]) -> dict[str, Any]: ...

def read_shape(filename: str, hdu_num: int) -> tuple[int, tuple[int, ...]]:
    """
    (bitpix, row-major shape) for an image HDU.

    Row-major means NAXISn reversed, matching ``Metadata.shape()``
    and the tensor paths -- not ``Metadata.image_info()``.
    """

def clear_shared_read_meta_cache() -> None: ...

def shared_meta_entry_count() -> int: ...
